FROM mongo
COPY init.json /init.json
CMD mongoimport --host mongodb --authenticationDatabase admin --username root --password pass12345 --db procrastination --collection lamps --type json --file /init.json --jsonArray
